AWSTemplateFormatVersion: 2010-09-09
Description: Provisions HIPAA Ready Environment in AWS - Stg
Metadata:
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in nested stacks
  Output:
    Description: N/A
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Staging VPC configuration
      Parameters:
      - StgVPCCIDRBlock
      - StgVPCSubnet1
      - StgVPCSubnet2
      - StgVPCFlowLogLogGroupRetention
    ParameterLabels:
      StgVPCCIDRBlock:
        default: Staging VPC CIDR block
      StgVPCSubnet1:
        default: Staging Subnet 1 CIDR block
      StgVPCSubnet2:
        default: Staging Subnet 2 CIDR block
      StgVPCFlowLogLogGroupRetention:
        default: Staging VPC log group retention days
Parameters:
  StgVPCCIDRBlock:
    Type: String
    Description: Staging VPC CIDR block.
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
  StgVPCSubnet1:
    Type: String
    Description: Staging VPC private subnet 1.
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
  StgVPCSubnet2:
    Type: String
    Description: Staging VPC private subnet 2.
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
  StgVPCFlowLogLogGroupRetention:
    Type: String
    Description: Staging VPC flow logs log group retention days.
Resources:
  StagingVPCFlowLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: !Ref StgVPCFlowLogLogGroupRetention
  StagingFlowLogsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowFlowLogs
            Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: 'sts:AssumeRole'
      Description: Staging Flow Logs Role
      Path: /
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                Resource: '*'
          PolicyName: Staging-Flow-Logs-Role
      Tags:
        - Key: Name
          Value: Staging VPC Flow Logs Role
        - Key: Purpose
          Value: Networking
  StgVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref StgVPCCIDRBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Staging VPC
        - Key: Purpose
          Value: Networking
    DependsOn:
      - StagingVPCFlowLogGroup
  StagingVPCFlowLogs:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      ResourceId: !Ref StgVPC
      ResourceType: VPC
      TrafficType: ALL
      DeliverLogsPermissionArn: !GetAtt 
        - StagingFlowLogsRole
        - Arn
      LogDestinationType: cloud-watch-logs
      LogGroupName: !Ref StagingVPCFlowLogGroup
      Tags:
        - Key: Name
          Value: Staging VPC Flow Logs
        - Key: Purpose
          Value: Networking
  StgCoreSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref StgVPCSubnet1
      VpcId: !Ref StgVPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Staging Core Subnet 1
        - Key: Purpose
          Value: Networking
  StgCoreSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref StgVPCSubnet2
      VpcId: !Ref StgVPC
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Staging Core Subnet 2
        - Key: Purpose
          Value: Networking
  StgPrivateRouteTable1:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref StgVPC
      Tags:
        - Key: Name
          Value: Staging VPC Private Route Table 1
        - Key: Purpose
          Value: Networking
  StgCore1RouteAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref StgPrivateRouteTable1
      SubnetId: !Ref StgCoreSubnet1
  StgCore2RouteAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref StgPrivateRouteTable1
      SubnetId: !Ref StgCoreSubnet2
  StgPrivateIPPrefixList:
    Type: AWS::EC2::PrefixList
    Properties: 
      AddressFamily: IPv4
      Entries: 
        - Cidr: !Ref StgVPCSubnet1
          Description: !Sub '${AWS::StackName}-CoreSubnet1'
        - Cidr: !Ref StgVPCSubnet2
          Description: !Sub '${AWS::StackName}-CoreSubnet2'
      MaxEntries: 2
      PrefixListName: !Sub '${AWS::StackName}-SubnetIPs'
      Tags: 
        - Key: Name
          Value: !Sub '${AWS::StackName}-SubnetIPs'
Outputs:
  StagingVPCSubnet1:
    Value: !Ref StgCoreSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-CoreSubnet1'
  StagingVPCSubnet2:
    Value: !Ref StgCoreSubnet2
    Export:
      Name: !Sub '${AWS::StackName}-CoreSubnet2'
  StagingVPCPrivateSubnet1CIDR:
    Value: !Ref StgVPCSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnet1CIDR'
  StagingVPCPrivateSubnet2CIDR:
    Value: !Ref StgVPCSubnet2
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnet2CIDR'
  SubnetsPrivate:
    Description: 'Subnets private'
    Value: !Join [',', [!Ref StgCoreSubnet1, !Ref StgCoreSubnet2]]
    Export:
      Name: !Sub '${AWS::StackName}-SubnetsPrivate'  
  StagingPrefixList:
    Description: 'Managed IP Prefix list'
    Value: !Ref StgPrivateIPPrefixList
    Export:
      Name: !Sub '${AWS::StackName}-PrefixList'  
  StagingVPC:
    Value: !Ref StgVPC
    Export:
      Name: !Sub '${AWS::StackName}-VPC'
  StagingPrivateRouteTable1:
    Value: !Ref StgPrivateRouteTable1
  Help:
    Description: For assistance or questions regarding this quickstart please email compliance-accelerator@amazon.com
    Value: ''
...
